[2023-03-27T03:09:46.766+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data scheduled__2023-03-16T00:00:00+00:00 [queued]>
[2023-03-27T03:09:46.776+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data scheduled__2023-03-16T00:00:00+00:00 [queued]>
[2023-03-27T03:09:46.777+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T03:09:46.777+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-03-27T03:09:46.777+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T03:09:46.791+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-16 00:00:00+00:00
[2023-03-27T03:09:46.799+0000] {standard_task_runner.py:55} INFO - Started process 85 to run task
[2023-03-27T03:09:46.802+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'projeto_agro', 'extract_data', 'scheduled__2023-03-16T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpgj4jmqz5']
[2023-03-27T03:09:46.803+0000] {standard_task_runner.py:83} INFO - Job 80: Subtask extract_data
[2023-03-27T03:09:46.884+0000] {task_command.py:389} INFO - Running <TaskInstance: projeto_agro.extract_data scheduled__2023-03-16T00:00:00+00:00 [running]> on host 264f1e537a4a
[2023-03-27T03:09:47.070+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=projeto_agro
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-16T00:00:00+00:00
[2023-03-27T03:10:02.389+0000] {logging_mixin.py:137} WARNING - /opt/airflow/dags/../../scripts/extract.py:27 DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
[2023-03-27T03:10:02.507+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 16, in extract
    extract.change_columns_year()
AttributeError: 'Extract' object has no attribute 'change_columns_year'
[2023-03-27T03:10:02.520+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=projeto_agro, task_id=extract_data, execution_date=20230316T000000, start_date=20230327T030946, end_date=20230327T031002
[2023-03-27T03:10:02.538+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 80 for task extract_data ('Extract' object has no attribute 'change_columns_year'; 85)
[2023-03-27T03:10:02.579+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-27T03:10:02.600+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
