[2023-03-27T21:00:46.944+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data manual__2023-03-27T21:00:42.683080+00:00 [queued]>
[2023-03-27T21:00:46.956+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data manual__2023-03-27T21:00:42.683080+00:00 [queued]>
[2023-03-27T21:00:46.956+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T21:00:46.956+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-03-27T21:00:46.957+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T21:00:46.983+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-27 21:00:42.683080+00:00
[2023-03-27T21:00:46.988+0000] {standard_task_runner.py:55} INFO - Started process 252 to run task
[2023-03-27T21:00:46.993+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'projeto_agro', 'extract_data', 'manual__2023-03-27T21:00:42.683080+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpady58w38']
[2023-03-27T21:00:46.994+0000] {standard_task_runner.py:83} INFO - Job 142: Subtask extract_data
[2023-03-27T21:00:47.097+0000] {task_command.py:389} INFO - Running <TaskInstance: projeto_agro.extract_data manual__2023-03-27T21:00:42.683080+00:00 [running]> on host 48ec747c45e3
[2023-03-27T21:00:47.202+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=projeto_agro
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T21:00:42.683080+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-27T21:00:42.683080+00:00
[2023-03-27T21:01:28.065+0000] {logging_mixin.py:137} WARNING - /opt/airflow/dags/../../scripts/extract.py:31 DtypeWarning: Columns (2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
[2023-03-27T21:01:45.650+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 19, in extract
    kwargs["ti"].xcom_push(
NameError: name 'kwargs' is not defined
[2023-03-27T21:01:45.669+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=projeto_agro, task_id=extract_data, execution_date=20230327T210042, start_date=20230327T210046, end_date=20230327T210145
[2023-03-27T21:01:45.684+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 142 for task extract_data (name 'kwargs' is not defined; 252)
[2023-03-27T21:01:45.776+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-27T21:01:45.804+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
