[2023-03-27T20:46:50.226+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data manual__2023-03-27T20:46:46.695643+00:00 [queued]>
[2023-03-27T20:46:50.235+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data manual__2023-03-27T20:46:46.695643+00:00 [queued]>
[2023-03-27T20:46:50.236+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T20:46:50.236+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-03-27T20:46:50.236+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T20:46:50.250+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-27 20:46:46.695643+00:00
[2023-03-27T20:46:50.253+0000] {standard_task_runner.py:55} INFO - Started process 134 to run task
[2023-03-27T20:46:50.256+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'projeto_agro', 'extract_data', 'manual__2023-03-27T20:46:46.695643+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp06dqylyz']
[2023-03-27T20:46:50.257+0000] {standard_task_runner.py:83} INFO - Job 138: Subtask extract_data
[2023-03-27T20:46:50.321+0000] {task_command.py:389} INFO - Running <TaskInstance: projeto_agro.extract_data manual__2023-03-27T20:46:46.695643+00:00 [running]> on host 48ec747c45e3
[2023-03-27T20:46:50.407+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=projeto_agro
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T20:46:46.695643+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-27T20:46:46.695643+00:00
[2023-03-27T20:47:06.561+0000] {logging_mixin.py:137} WARNING - /opt/airflow/dags/../../scripts/extract.py:31 DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
[2023-03-27T20:47:14.389+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fastparquet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 17, in extract
    dict_files_name=extract.save_data_raw()
  File "/opt/airflow/dags/../../scripts/extract.py", line 46, in save_data_raw
    self.infos_countries.to_parquet('gs://data_raw_area_project_agro/' + dict_files_name['path_file_countries'], storage_options={'token':'/opt/credentials/zoomcamp-374100-a34bc7914122.json'}, engine='fastparquet')
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/frame.py", line 2975, in to_parquet
    return to_parquet(
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 426, in to_parquet
    impl = get_engine(engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 65, in get_engine
    return FastParquetImpl()
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parquet.py", line 266, in __init__
    fastparquet = import_optional_dependency(
  File "/usr/local/lib/python3.9/site-packages/pandas/compat/_optional.py", line 144, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
[2023-03-27T20:47:14.419+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=projeto_agro, task_id=extract_data, execution_date=20230327T204646, start_date=20230327T204650, end_date=20230327T204714
[2023-03-27T20:47:14.432+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 138 for task extract_data (Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.; 134)
[2023-03-27T20:47:14.464+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-27T20:47:14.486+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
